### ISSUE TITLE
Create and format partner course index pages

### ISSUE THREAD

**Issue by allanhaggett** [allanhaggett/wp-bcgov-learning-hub#18]

**Comment by LeannaHill** [comment]
Hey @allanhaggett I've added two partners in the partner spreadsheet within Teams that should help with this too. Would you like me to start asking for Ministry logos, or are those relatively easy to access? Thinking that partners without logos get a ministry logo.

**Comment by allanhaggett** [comment]
Thanks @LeannaHill I'll add them to the site today. If you could ask for logos, that would save having to go look for an appropriate file and then maybe be wrong...
