### ISSUE TITLE
Format footer for color and structure

### ISSUE THREAD

**Issue by allanhaggett** [allanhaggett/wp-bcgov-learning-hub#8]

**Comment by allanhaggett** [comment]
https://github.com/allanhaggett/twentytwentyone-learnhub/commit/f326b1f0fc055f5e2e4c62b3ff3afcd26a009e6c

**Comment by LeannaHill** [comment]
@allanhaggett  can you re-open this to include the links/design that Gek-Bee proposed, along with Territorial acknowledgement in the footer? TY!

**Comment by allanhaggett** [comment]
I closed this one as it's a specific issue that I tied to a specific code change.

Adding the design flats provided by Gek-Bee should probably be uploaded to issue #13 so that they're tied to that (but since the files already live in Teams, I'm not sure having them in multiple places will help). A separate issue should be created along the lines of "Format footer based on Gek-Bee's design" or something.
